name: Publish Packages

on:
  workflow_run:
    workflows: ["Build & Test"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@auto-engineer'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: version packages"
          title: "chore: version packages"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Published Packages
        if: success()
        id: get_packages
        run: |
          # Debug: Show raw JSON output
          echo "Raw JSON output:"
          pnpm changeset status --json
          
          # Get packages that were published in this release
          PACKAGES=$(pnpm changeset status --json | jq -r '.releases | to_entries[] | select(.value.type == "major" or .value.type == "minor" or .value.type == "patch") | "\(.value.name)@\(.value.newVersion)"')
          echo "packages<<EOF" >> $GITHUB_OUTPUT
          echo "$PACKAGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Configure Git
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Create Tags
        if: success()
        run: |
          COMMIT=$(git rev-parse HEAD)
          while IFS= read -r package; do
            if [[ $package == @auto-engineer/* ]]; then
              name=$(echo $package | cut -d'@' -f1)
              version=$(echo $package | cut -d'@' -f2)
              tag="${name#@auto-engineer/}-v${version}"
              git tag -a "$tag" -m "Release $package" $COMMIT
              git push origin "$tag"
            fi
          done <<< "${{ steps.get_packages.outputs.packages }}" 